### ISSUE TITLE
Review changed functions within testsuite commit

### ISSUE THREAD

**Issue by mitko501** [crocs-muni/eacirc-streams#12]
Hello, I would like to ask you to review my changes to crypto functions done in testsuite PR. The changes I done was mostly done so that I found reference implementation and compare it using diff with our implementation and look for differences. 

The tests are passing with test vectors I found, so what I would like to get is just some feedback that I haven't done something stupid for example completely ruined our round reduction or something like that. 

Whole PR: https://github.com/crocs-muni/eacirc-streams/pull/11

Functions changed:
- [ ] SIMD - There was problem with unsigned long having 8 Bytes, but function relied on the fact that type used have 4 Bytes (commit: https://github.com/crocs-muni/eacirc-streams/pull/11/commits/d29420dac69697c94461939650ccc1860ff5742b)
- [ ] Lesamnta - Problem was that variable `i` was fixed in our implementation while in reference implementation I found `i` was changed in loop, so I needed to change it to loop (https://github.com/crocs-muni/eacirc-streams/pull/11/commits/38ebfc7f3c9cd74071652fef9f85036e4d72b499)
- [ ] JH - Probably I found different implementation, but I was not able to find test vectors for that one we had (commit: https://github.com/crocs-muni/eacirc-streams/pull/11/commits/f28c033ad19f72fd4905044d4a4a697a7712610a)
- [ ] Hamsi - Again maybe different implementation: (https://github.com/crocs-muni/eacirc-streams/pull/11/commits/82b0bfa8a46a6f92abbabb20ed04fb048c1adb1f)
- [ ] Decim - We had two implementations of Decim marked decim-v2 and decim-128. I found that both implementations are identical. So I needed to update decim-v2 to actually use decim-v2 implementation not decim 128. This can ruin results we obtained for decim until now. (https://github.com/crocs-muni/eacirc-streams/pull/11/commits/ef7e00e253e79ca63cb33d123f009b0e2fa31824)

**Comment by Bender250** [comment]
We did this together ;).
